INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation 5');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Xbox Series S');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Xbox Series X');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Nintendo Switch');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Super Nintendo');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'NES');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation 4');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Xbox One');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Nintendo Wii U');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation 3');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Xbox 360');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Nintendo Wii');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation 2');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Xbox');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Nintendo GameCube');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Nintendo 64');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Sega Saturn');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation Portable');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Game Boy Advance');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Dreamcast');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Nintendo 3DS');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation Vita');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Game Boy Color');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Nintendo DS');
INSERT INTO socialapp.consoles (id, name) VALUES (uuid_generate_v4(), 'Playstation Portable Go');
