INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Afghanistan', 'AF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Albania', 'AL');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Algeria', 'DZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'American Samoa', 'AS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Andorra', 'AD');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Angola', 'AO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Anguilla', 'AI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Antarctica', 'AQ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Antigua and Barbuda', 'AG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Argentina', 'AR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Armenia', 'AM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Aruba', 'AW');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Australia', 'AU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Austria', 'AT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Azerbaijan', 'AZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bahamas', 'BS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bahrain', 'BH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bangladesh', 'BD');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Barbados', 'BB');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Belarus', 'BY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Belgium', 'BE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Belize', 'BZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Benin', 'BJ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bermuda', 'BM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bhutan', 'BT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bosnia and Herzegovina', 'BA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Botswana', 'BW');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bouvet Island', 'BV');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Brazil', 'BR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'British Indian Ocean Territory', 'IO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Brunei Darussalam', 'BN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Bulgaria', 'BG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Burkina Faso', 'BF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Burundi', 'BI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cambodia', 'KH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cameroon', 'CM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Canada', 'CA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cape Verde', 'CV');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cayman Islands', 'KY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Central African Republic', 'CF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Chad', 'TD');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Chile', 'CL');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'China', 'CN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Christmas Island', 'CX');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cocos (Keeling) Islands', 'CC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Colombia', 'CO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Comoros', 'KM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Congo', 'CG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cook Islands', 'CK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Costa Rica', 'CR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Croatia', 'HR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cuba', 'CU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Cyprus', 'CY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Czech Republic', 'CZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Denmark', 'DK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Djibouti', 'DJ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Dominica', 'DM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Dominican Republic', 'DO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Ecuador', 'EC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Egypt', 'EG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'El Salvador', 'SV');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Equatorial Guinea', 'GQ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Eritrea', 'ER');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Estonia', 'EE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Ethiopia', 'ET');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Falkland Islands (Malvinas)' ,'FK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Faroe Islands', 'FO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Fiji', 'FJ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Finland', 'FI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'France', 'FR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'French Guiana', 'GF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'French Polynesia', 'PF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'French Southern Territories', 'TF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Gabon', 'GA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Gambia', 'GM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Georgia', 'GE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Germany', 'DE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Ghana', 'GH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Gibraltar', 'GI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Greece', 'GR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Greenland', 'GL');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Grenada', 'GD');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Guadeloupe', 'GP');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Guam', 'GU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Guatemala', 'GT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Guernsey', 'GG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Guinea', 'GN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Guinea-Bissau', 'GW');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Guyana', 'GY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Haiti', 'HT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Heard Island and McDonald Islands', 'HM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Holy See (Vatican City State)' ,'VA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Honduras', 'HN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Hong Kong', 'HK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Hungary', 'HU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Iceland', 'IS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'India', 'IN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Indonesia', 'ID');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Iran', 'IR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Iraq', 'IQ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Ireland', 'IE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Isle of Man', 'IM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Italy', 'IT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Jamaica', 'JM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Japan', 'JP');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Jersey', 'JE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Jordan', 'JO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Kazakhstan', 'KZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Kenya', 'KE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Kiribati', 'KI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Kuwait', 'KW');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Kyrgyzstan', 'KG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Lao Peoples Democratic Republic', 'LA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Latvia', 'LV');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Lebanon', 'LB');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Lesotho', 'LS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Liberia', 'LR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Libya', 'LY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Liechtenstein', 'LI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Lithuania', 'LT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Luxembourg', 'LU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Macao', 'MO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Madagascar', 'MG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Malawi', 'MW');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Malaysia', 'MY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Maldives', 'MV');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Mali', 'ML');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Malta', 'MT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Marshall Islands', 'MH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Martinique', 'MQ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Mauritania', 'MR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Mauritius', 'MU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Mayotte', 'YT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Mexico', 'MX');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Monaco', 'MC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Mongolia', 'MN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Montenegro', 'ME');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Montserrat', 'MS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Morocco', 'MA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Mozambique', 'MZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Myanmar', 'MM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Namibia', 'NA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Nauru', 'NR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Nepal', 'NP');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Netherlands', 'NL');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'New Caledonia', 'NC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'New Zealand', 'NZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Nicaragua', 'NI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Niger', 'NE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Nigeria', 'NG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Niue', 'NU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Norfolk Island', 'NF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Northern Mariana Islands', 'MP');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Norway', 'NO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Oman', 'OM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Pakistan', 'PK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Palau', 'PW');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Palestine', 'PS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Panama', 'PA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Papua New Guinea', 'PG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Paraguay', 'PY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Peru', 'PE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Philippines', 'PH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Pitcairn', 'PN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Poland', 'PL');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Portugal', 'PT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Puerto Rico', 'PR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Qatar', 'QA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Romania', 'RO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Russian Federation', 'RU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Rwanda', 'RW');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Saint Kitts and Nevis', 'KN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Saint Lucia', 'LC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Saint Martin (French part)' ,'MF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Saint Pierre and Miquelon', 'PM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Samoa', 'WS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'San Marino', 'SM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Sao Tome and Principe', 'ST');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Saudi Arabia', 'SA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Senegal', 'SN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Serbia', 'RS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Seychelles', 'SC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Sierra Leone', 'SL');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Singapore', 'SG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Sint Maarten (Dutch part)' ,'SX');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Slovakia', 'SK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Slovenia', 'SI');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Solomon Islands', 'SB');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Somalia', 'SO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'South Africa', 'ZA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'South Sudan', 'SS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Spain', 'ES');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Sri Lanka', 'LK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'State of Palestine', 'PS');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Sudan', 'SD');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Suriname', 'SR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Swaziland', 'SZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Sweden', 'SE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Switzerland', 'CH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Syrian Arab Republic', 'SY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Tajikistan', 'TJ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Thailand', 'TH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Timor-Leste', 'TL');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Togo', 'TG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Tokelau', 'TK');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Tonga', 'TO');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Trinidad and Tobago', 'TT');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Tunisia', 'TN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Turkey', 'TR');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Turkmenistan', 'TM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Turks and Caicos Islands', 'TC');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Tuvalu', 'TV');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Uganda', 'UG');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Ukraine', 'UA');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'United Arab Emirates', 'AE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'United Kingdom', 'GB');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'United States', 'US');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'United States Minor Outlying Islands', 'UM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Uruguay', 'UY');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Uzbekistan', 'UZ');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Vanuatu', 'VU');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Viet Nam', 'VN');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Wallis and Futuna', 'WF');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Western Sahara', 'EH');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Yemen', 'YE');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Zambia', 'ZM');
INSERT INTO socialapp.countries (id, name, code) VALUES (uuid_generate_v4(), 'Zimbabwe', 'ZW');