INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'RPG');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Metroidvania');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Open World');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Platform');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Puzzle');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Action');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Adventure');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Horror');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Shooting');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'FPS');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Walking Simulator');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Fighting');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Third Person Shooter');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Souls');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Side Scrolling Action');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'First Person Shooter');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Racing');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Terror');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Multiplayer');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Sports');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Sandbox');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Stealth');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Strategy');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Survival');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Casual');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Simulation');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'MMO');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'MOBA');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Hack and Slash');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Beat em up');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Cards');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Party');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Rhythm');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Battle Royale');
INSERT INTO socialapp.genres (id, name) VALUES (uuid_generate_v4(), 'Visual Novel');