ALTER TABLE users
ADD COLUMN access_failed_count INT DEFAULT 0,
ADD COLUMN lockout_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN lockout_end TIMESTAMP,
ADD COLUMN username VARCHAR(20) UNIQUE,
ADD COLUMN two_factor_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN theme VARCHAR(20)
